name: UltimateJQMessages
main: nl.chimpgamer.ultimatejqmessages.paper.UltimateJQMessagesPlugin
version: ${version}
description: Ultimate Join Quit Messages plugin
api-version: '1.19'

softdepend: []

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.21
  - org.jetbrains.kotlin:kotlin-reflect:1.8.21
  - org.jetbrains.exposed:exposed-core:0.41.1
  - org.jetbrains.exposed:exposed-dao:0.41.1
  - org.jetbrains.exposed:exposed-jdbc:0.41.1
  - org.xerial:sqlite-jdbc:3.42.0.0
  - org.mariadb.jdbc:mariadb-java-client:3.1.4
  - dev.dejvokep:boosted-yaml:1.3.1
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.3
  - cloud.commandframework:cloud-paper:1.8.3
  - cloud.commandframework:cloud-minecraft-extras:1.8.3