name: UltimateJQMessages
main: nl.chimpgamer.ultimatejqmessages.paper.UltimateJQMessagesPlugin
version: ${version}
description: Ultimate Join Quit Messages plugin
api-version: '1.19'

softdepend:
  - PlaceholderAPI
  - MiniPlaceholders

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.23
  - org.jetbrains.kotlin:kotlin-reflect:1.9.23
  - org.jetbrains.exposed:exposed-core:0.49.0
  - org.jetbrains.exposed:exposed-dao:0.49.0
  - org.jetbrains.exposed:exposed-jdbc:0.49.0
  - org.xerial:sqlite-jdbc:3.44.1.0
  - org.mariadb.jdbc:mariadb-java-client:3.3.1
  - dev.dejvokep:boosted-yaml:1.3.4
  - cloud.commandframework:cloud-paper:1.8.4
  - cloud.commandframework:cloud-minecraft-extras:1.8.4
  - cloud.commandframework:cloud-kotlin-coroutines:1.8.4
  - com.zaxxer:HikariCP:5.1.0