storage:
  type: SQLITE
  host: localhost
  port: 3306
  database: ultimatejqmessages
  username: ultimatejqmessages
  password: ultimatejqmessages
  properties:
    useUnicode: true
    characterEncoding: utf8

join_messages:
  custom:
    max_length: 256
  cooldown: -1
  display-name-format: '<player_display_name>'

quit_messages:
  custom:
    max_length: 256
  cooldown: -1
  display-name-format: '<player_display_name>'

config-version: 2