storage:
  type: SQLITE
  host: localhost
  port: 3306
  database: ultimatejqmessages
  username: ultimatejqmessages
  password: password
  properties:
    useUnicode: true
    characterEncoding: utf8

join_messages:
  custom:
    max_length: 256
  cooldown: -1
  delay: -1
  display-name-format: '<player_display_name>'
  prefix: '<dark_green><bold>Join</bold></dark_green> <dark_gray>»</dark_gray> '
  command:
    name: joinmessages
    aliases:
      - joinmessage

quit_messages:
  custom:
    max_length: 256
  cooldown: -1
  delay: -1
  display-name-format: '<player_display_name>'
  prefix: '<dark_red><bold>Quit</bold></dark_red> <dark_gray>»</dark_gray> '
  command:
    name: quitmessages
    aliases:
      - quitmessage

config-version: 5