storage:
  type: SQLITE
  host: localhost
  port: 3306
  database: ultimatetags
  username: ultimatetags
  password: ultimatetags
  properties:
    useUnicode: true
    characterEncoding: utf8

join_messages:
  custom:
    max_length: 256
  cooldown: -1
  display-name-format: '<player_display_name>'

quit_messages:
  custom:
    max_length: 256
  cooldown: -1
  display-name-format: '<player_display_name>'

config-version: 2