storage:
  type: SQLITE
  host: localhost
  port: 3306
  database: ultimatejqmessages
  username: ultimatejqmessages
  password: password
  properties:
    useUnicode: true
    characterEncoding: utf8

join_messages:
  custom:
    max_length: 256
  cooldown: -1
  display-name-format: '<player_display_name>'
  prefix: '<b><dark_green>Join</dark_green></b> <dark_gray>»</dark_gray>'

quit_messages:
  custom:
    max_length: 256
  cooldown: -1
  display-name-format: '<player_display_name>'
  prefix: '<b><dark_red>Quit</dark_red></b> <dark_gray>»</dark_gray>'

config-version: 4